name: daily compile

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: mac
    steps:
    - name: checkout repo content
      uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: execute new products
      run: python scripts/load_new_products.py

    - name: execute gatherer build
      run: python scripts/generate_original_printing_details.py
